# Generated by Django 5.2.5 on 2025-08-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
