# Generated by Django 5.2.5 on 2025-08-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
