# Generated by Django 4.2.1 on 2023-06-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(default='https://thumbs.dreamstime.com/b/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132482953.jpg'),
        ),
    ]
