# Generated by Django 4.2.1 on 2023-06-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_course_profile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.URLField(default='https://thumbs.dreamstime.com/b/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132482953.jpg'),
        ),
    ]
