# Generated by Django 4.2.2 on 2023-07-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_forumcategory_forumtopic_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
