# Generated by Django 4.2.2 on 2023-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_forumtopic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
