# Generated by Django 4.2.2 on 2023-07-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_forumtopic_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumtopic',
            old_name='post_liked',
            new_name='topic_liked',
        ),
    ]
