# Generated by Django 4.2.2 on 2023-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_rename_post_liked_forumtopic_topic_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(default='General description'),
            preserve_default=False,
        ),
    ]
