# Generated by Django 4.2.2 on 2023-08-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_quiz_quizattempt_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_qty',
            field=models.IntegerField(default=1),
        ),
    ]
