# Generated by Django 4.2.2 on 2023-08-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_quiz_questions_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='academy.course'),
            preserve_default=False,
        ),
    ]
