# Generated by Django 4.2.2 on 2023-08-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_quiz_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
    ]
