# Generated by Django 4.2.2 on 2023-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_remove_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
