# Generated by Django 4.2.1 on 2023-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_edited_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edited_content',
        ),
        migrations.AddField(
            model_name='post',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
