# Generated by Django 4.1.7 on 2023-03-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_category_listing_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url_image',
            field=models.URLField(default='https://thumbs.dreamstime.com/b/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132482953.jpg'),
        ),
    ]
