# Generated by Django 4.1.7 on 2023-03-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='amount',
        ),
    ]
