# Generated by Django 4.1.7 on 2023-03-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='qty_bids',
            field=models.IntegerField(default=1),
        ),
    ]
