# Generated by Django 4.1.7 on 2023-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_watchlist_added_at_remove_watchlist_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='qty_bids',
            field=models.IntegerField(default=0),
        ),
    ]
